acme_countries:
    resource: "@AcmeTestBundle/Controller/CountriesController.php"
    prefix: /acme/countries
    type: annotation
    options:
        expose: true

acme_country:
    resource: "@AcmeTestBundle/Controller/Api/Rest/CountryController.php"
    prefix: api/rest/{version}/country
    type: rest
    requirements:
        version: latest|v1
    defaults:
        version: latest